-- AUTO-GENERATED BY PRISMA
CREATE DATABASE IF NOT EXISTS animedb;

USE animedb;


-- CreateTable
CREATE TABLE IF NOT EXISTS `Role` (
    `role_id` INTEGER NOT NULL AUTO_INCREMENT,
    `role_name` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Role_role_name_key`(`role_name`),
    PRIMARY KEY (`role_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `User` (
    `user_id` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `role_id` INTEGER NOT NULL,

    UNIQUE INDEX `User_username_key`(`username`),
    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`user_id`),
    CONSTRAINT `User_role_id_fkey` FOREIGN KEY (`role_id`) REFERENCES `Role`(`role_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `Session` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `tokenHash` VARCHAR(191) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Session_tokenHash_key`(`tokenHash`),
    INDEX `Session_userId_idx`(`userId`),
    PRIMARY KEY (`id`),
    CONSTRAINT `Session_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `Anime` (
    `anime_id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `cover_image` VARCHAR(191) NOT NULL DEFAULT '',
    `genre` VARCHAR(191) NOT NULL,
    `episodes` INTEGER NOT NULL,
    `release_year` INTEGER NOT NULL,
    `description` TEXT NOT NULL,

    UNIQUE INDEX `Anime_title_key`(`title`),
    UNIQUE INDEX `Anime_title_release_year_key`(`title`, `release_year`),
    PRIMARY KEY (`anime_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `Watchlist` (
    `watchlist_id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `anime_id` INTEGER NOT NULL,
    `status` ENUM('PLAN_TO_WATCH', 'WATCHING', 'COMPLETED', 'DROPPED', 'ON_HOLD') NOT NULL,

    INDEX `Watchlist_user_id_idx`(`user_id`),
    INDEX `Watchlist_anime_id_idx`(`anime_id`),
    UNIQUE INDEX `Watchlist_user_id_anime_id_key`(`user_id`, `anime_id`),
    PRIMARY KEY (`watchlist_id`),
    CONSTRAINT `Watchlist_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `Watchlist_anime_id_fkey` FOREIGN KEY (`anime_id`) REFERENCES `Anime`(`anime_id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE IF NOT EXISTS `User_Rating` (
    `rating_id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_id` INTEGER NOT NULL,
    `anime_id` INTEGER NOT NULL,
    `rating_score` INTEGER NOT NULL,
    `rated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `User_Rating_user_id_idx`(`user_id`),
    INDEX `User_Rating_anime_id_idx`(`anime_id`),
    UNIQUE INDEX `User_Rating_user_id_anime_id_key`(`user_id`, `anime_id`),
    PRIMARY KEY (`rating_id`),
    CONSTRAINT `User_Rating_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `User`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `User_Rating_anime_id_fkey` FOREIGN KEY (`anime_id`) REFERENCES `Anime`(`anime_id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- END AUTOGENERATION
-- START DEFAULT VALUES --

-- Roles
INSERT INTO Role (role_id, role_name) VALUES
  (1, 'USER'),
  (2, 'ADMIN')
ON DUPLICATE KEY UPDATE role_name = role_name;

-- Anime
INSERT INTO Anime (title, genre, episodes, release_year, description) VALUES
  ('Attack on Titan',                 'Action',     87,   2013, 'Humanity fights Titans.'),
  ('Death Note',                      'Thriller',   37,   2006, 'A notebook that kills.'),
  ('Fullmetal Alchemist: Brotherhood','Adventure',  64,   2009, 'Alchemy and sacrifice.'),
  ('Demon Slayer',                    'Action',     55,   2019, 'Demon hunting story.'),
  ('Jujutsu Kaisen',                  'Action',     47,   2020, 'Curses and sorcery.'),
  ('Naruto',                          'Adventure',  220,  2002, 'A ninja''s journey.'),
  ('Naruto Shippuden',                'Adventure',  500,  2007, 'Continuation of Naruto.'),
  ('One Piece',                       'Adventure',  1000, 1999, 'Pirates seeking treasure.'),
  ('Bleach',                          'Action',     366,  2004, 'Soul reapers.'),
  ('Tokyo Ghoul',                     'Dark',       48,   2014, 'Half-ghoul story.'),
  ('Chainsaw Man',                    'Action',     12,   2022, 'Devils and chaos.'),
  ('Spy x Family',                    'Comedy',     25,   2022, 'Fake family espionage.'),
  ('My Hero Academia',                'Superhero',  138,  2016, 'Heroes in training.'),
  ('Steins;Gate',                     'Sci-Fi',     24,   2011, 'Time travel thriller.'),
  ('Re:Zero',                         'Fantasy',    50,   2016, 'Death loop fantasy.'),
  ('Vinland Saga',                    'Historical', 48,   2019, 'Viking revenge story.'),
  ('Frieren: Beyond Journey''s End',  'Fantasy',    28,   2023, 'Life after the hero.'),
  ('Mob Psycho 100',                  'Action',     37,   2016, 'Psychic powers.'),
  ('Code Geass',                      'Mecha',      50,   2006, 'Rebellion and strategy.'),
  ('Sword Art Online',                'Isekai',     96,   2012, 'Trapped in a game.')
ON DUPLICATE KEY UPDATE title = title;

-- Test user (password is 'password123')
INSERT INTO User (username, email, password, role_id) VALUES
  ('testuser', 'test@example.com', '$2b$12$DojQ.D/I9lP2VnI.CGGqmeURiThgrFXTPDMtU8Q.FiKKAY4S/aB0i', 1)
ON DUPLICATE KEY UPDATE username = username;

INSERT INTO User (username, email, password, role_id) VALUES
  ('admin', 'admin@example.com', '$2b$12$DojQ.D/I9lP2VnI.CGGqmeURiThgrFXTPDMtU8Q.FiKKAY4S/aB0i', 2)
ON DUPLICATE KEY UPDATE username = username;


-- Default watchlist for test user
INSERT INTO Watchlist (user_id, anime_id, status)
SELECT u.user_id, a.anime_id, v.status
FROM User u
JOIN (
    SELECT 'Attack on Titan'                  AS title, 'COMPLETED'     AS status
    UNION ALL SELECT 'Death Note',                       'COMPLETED'
    UNION ALL SELECT 'Fullmetal Alchemist: Brotherhood', 'COMPLETED'
    UNION ALL SELECT 'Jujutsu Kaisen',                   'WATCHING'
    UNION ALL SELECT 'Demon Slayer',                     'WATCHING'
    UNION ALL SELECT 'Naruto',                           'COMPLETED'
    UNION ALL SELECT 'Naruto Shippuden',                 'PLAN_TO_WATCH'
    UNION ALL SELECT 'One Piece',                        'ON_HOLD'
    UNION ALL SELECT 'Steins;Gate',                      'COMPLETED'
    UNION ALL SELECT 'Vinland Saga',                     'PLAN_TO_WATCH'
) AS v ON 1=1
JOIN Anime a ON a.title = v.title
WHERE u.username = 'testuser'
ON DUPLICATE KEY UPDATE status = status;

/*
* Views
*/

-- View detailed list of users anime watchlist with list of show details
CREATE OR REPLACE VIEW user_watchlist_info AS
SELECT u.user_id, u.username, a.anime_id, a.title, a.genre, a.release_year, a.description, w.watchlist_id
FROM Watchlist w
LEFT JOIN User u ON w.user_id = u.user_id
LEFT JOIN Anime a ON a.anime_id = w.anime_id;


/*
* Triggers
*/


/*
* Procedures/Functions
*/


/*
* Cursors
*/
